services:
  forecast:
    image: docker.io/ciaa/fast-forecast:v0.1.0
    ports:
      - "8000:8000"
    environment:
      MLFLOW_REQUIRED_ENVS: /run/secrets/mlflow_s3_password
    secrets:
      - mlflow_s3_password
secrets:
  mlflow_s3_password:
    file: credentials.json