apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-s3-credentials
  namespace: default
data:
  credentials.json: |
    {
      "AWS_ACCESS_KEY_ID": "${AWS_ACCESS_KEY_ID}",
      "AWS_SECRET_ACCESS_KEY": "${AWS_SECRET_ACCESS_KEY}",
      "MLFLOW_S3_ENDPOINT_URL": "${MLFLOW_S3_ENDPOINT_URL}",
      "AWS_DEFAULT_REGION": "${AWS_DEFAULT_REGION}"
    }  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fast-api
  template:
    metadata:
      labels:
        app: fast-api
    spec:
      containers:
        - name: fast-api
          image: ciaa/forecast-service:${VERSION}
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_S3_PASSWORD_FILE
              value: /etc/config/credentials.json
          volumeMounts:
            - name: json-configmap-volume
              mountPath: /etc/config
      volumes:
        - name: json-configmap-volume
          configMap:
            name: mlflow-s3-credentials      
---
apiVersion: v1
kind: Service
metadata:
  name: fast-api-service
spec:
  selector:
    app: fast-api
  ports:
  - port: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-controller
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/app"
        backend:
          service:
            name: fast-api-service
            port:
              number: 8000